require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RobotsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Robot. As you add validations to Robot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name:"美人儿",price:11}

  }

  let(:invalid_attributes) {
    {name:"fwerek"}

  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RobotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all robots as @robots" do
      robot = Robot.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:robots)).to eq([robot])
    end
  end

  describe "GET #show" do
    it "assigns the requested robot as @robot" do
      robot = Robot.create! valid_attributes
      get :show, params: {id: robot.to_param}, session: valid_session
      expect(assigns(:robot)).to eq(robot)
    end
  end

  describe "GET #new" do
    it "assigns a new robot as @robot" do
      get :new, params: {}, session: valid_session
      expect(assigns(:robot)).to be_a_new(Robot)
    end
  end

  describe "GET #edit" do
    it "assigns the requested robot as @robot" do
      robot = Robot.create! valid_attributes
      get :edit, params: {id: robot.to_param}, session: valid_session
      expect(assigns(:robot)).to eq(robot)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Robot" do
        expect {
          post :create, params: {robot: valid_attributes}, session: valid_session
        }.to change(Robot, :count).by(1)
      end

      it "assigns a newly created robot as @robot" do
        post :create, params: {robot: valid_attributes}, session: valid_session
        expect(assigns(:robot)).to be_a(Robot)
        expect(assigns(:robot)).to be_persisted
      end

      it "redirects to the created robot" do
        post :create, params: {robot: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Robot.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved robot as @robot" do
        post :create, params: {robot: invalid_attributes}, session: valid_session
        expect(assigns(:robot)).to be_a_new(Robot)
      end

      it "re-renders the 'new' template" do
        post :create, params: {robot: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name:"战士",price:131}
      }

      it "updates the requested robot" do
        robot = Robot.create! valid_attributes
        put :update, params: {id: robot.to_param, robot: new_attributes}, session: valid_session
        robot.reload
        {name:"战士",price:444}
      end

      it "assigns the requested robot as @robot" do
        robot = Robot.create! valid_attributes
        put :update, params: {id: robot.to_param, robot: valid_attributes}, session: valid_session
        expect(assigns(:robot)).to eq(robot)
      end

      it "redirects to the robot" do
        robot = Robot.create! valid_attributes
        put :update, params: {id: robot.to_param, robot: valid_attributes}, session: valid_session
        expect(response).to redirect_to(robot)
      end
    end

    context "with invalid params" do
      it "assigns the robot as @robot" do
        robot = Robot.create! valid_attributes
        put :update, params: {id: robot.to_param, robot: invalid_attributes}, session: valid_session
        expect(assigns(:robot)).to eq(robot)
      end

      it "re-renders the 'edit' template" do
        robot = Robot.create! valid_attributes
        put :update, params: {id: robot.to_param, robot: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested robot" do
      robot = Robot.create! valid_attributes
      expect {
        delete :destroy, params: {id: robot.to_param}, session: valid_session
      }.to change(Robot, :count).by(-1)
    end

    it "redirects to the robots list" do
      robot = Robot.create! valid_attributes
      delete :destroy, params: {id: robot.to_param}, session: valid_session
      expect(response).to redirect_to(robots_url)
    end
  end

end
